events {}

http {

    resolver 8.8.8.8;

    upstream backend {
        server techstore-flask-api.onrender.com:443;
        server techstore-flask-api.onrender.com:443 backup;
    }

    server {
        listen 80;

        location / {

            proxy_pass https://backend;

            proxy_ssl_server_name on;

            proxy_next_upstream error timeout http_500 http_502 http_503 http_504;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}