events {}

http {

    resolver 8.8.8.8 ipv6=off;

    server {
        listen 80;

        location / {

            proxy_pass https://techstore-flask-api.onrender.com;

            proxy_ssl_server_name on;
            proxy_set_header Host techstore-flask-api.onrender.com;

            proxy_next_upstream error timeout http_500 http_502 http_503 http_504;
        }

        error_page 502 503 504 = @backup;

        location @backup {
            proxy_pass https://techstore-flask-api.onrender.com;

            proxy_ssl_server_name on;
            proxy_set_header Host api-respaldo.onrender.com;
        }
    }
}